version: '3.8'

services:
  postgres:
    hostname: postgres
    image: postgres:14
    restart: always
    volumes:
      - postgres-data:/path/to/postgres/data
    container_name: my-postgres
    environment:
      POSTGRES_DB: bookStoreApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - shared-net



  spring-app:
    image: bookstoreapp-0.0.1:latest
    container_name: bookstoreapp-0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/book-store
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - shared-net

volumes:
  postgres-data:

networks:
  shared-net:
    driver: bridge